#pragma once

namespace affect {

enum Type {
    unknown = -1, // don't touch
    none = 0, // don't touch

    acid_breath,
    age,
    armor,
    bless,
    blindness,
    blood_blade,
    blood_moon,
    calm,
    change_sex,
    channel,
    charm_person,
    chill_touch,
    curse,
    darkness,
    dazzling_light,
    detect_evil,
    detect_good,
    detect_hidden,
    detect_invis,
    detect_magic,
    divine_regeneration,
    enchant_armor,
    enchant_weapon,
    faerie_fire,
    fear,
    fire_breath,
    fireproof,
    flame_blade,
    flameshield,
    fly,
    frenzy,
    frost_blade,
    giant_strength,
    haste,
    invis,
    mass_invis,
    night_vision,
    pass_door,
    plague,
    poison,
    protection_evil,
    protection_good,
    rayban,
    regeneration,
    sanctuary,
    shield,
    shock_blade,
    sleep,
    slow,
    smokescreen,
    steel_mist,
    stone_skin,
    talon,
    weaken,
    berserk,
    dirt_kicking,
    hide,
    meditation,
    sneak,
    sheen,
    focus,
    paralyze,
    ironskin,
    barrier,
    dazzle,
    midnight,
    shadow_form,
    hex,
    bone_wall,
    hammerstrike,
    force_shield,

    size, // don't touch
    first = 0 // don't touch
};

} // namespace affect

