#pragma once

namespace affect {

enum class type {
    unknown = -1, // don't touch
    none = 0, // don't touch

    acid_breath,
    age,
    armor,
    bless,
    blindness,
    blood_moon,
    calm,
    change_sex,
    channel,
    charm_person,
    chill_touch,
    curse,
    darkness,
    dazzling_light,
    detect_evil,
    detect_good,
    detect_hidden,
    detect_invis,
    detect_magic,
    divine_regeneration,
    enchant_armor,
    enchant_weapon,
    faerie_fire,
    fear,
    fire_breath,
    fireproof,
    flameshield,
    fly,
    frenzy,
    giant_strength,
    haste,
    invis,
    mass_invis,
    night_vision,
    pass_door,
    plague,
    poison,
    protection_evil,
    protection_good,
    rayban,
    regeneration,
    sanctuary,
    shield,
    sleep,
    slow,
    smokescreen,
    steel_mist,
    stone_skin,
    talon,
    weaken,
    berserk,
    dirt_kicking,
    hide,
    meditation,
    sneak,
    sheen,
    focus,
    paralyze,
    ironskin,
    barrier,
    dazzle,
    midnight,
    shadow_form,
    hex,
    bone_wall,
    hammerstrike,
    force_shield,

    // weapon flags
    weapon_acidic,
    weapon_flaming,
    weapon_frost,
    weapon_vampiric,
    weapon_sharp,
    weapon_vorpal,
    weapon_two_hands,
    weapon_shocking,

    // obj prefixes
    obj_prefix_solar,
    obj_prefix_astral,
    obj_prefix_lunar,
    obj_prefix_windy,
    obj_prefix_healthy,
    obj_prefix_hearty,
    obj_prefix_stalwart,
    obj_prefix_mystical,
    obj_prefix_magical,
    obj_prefix_lucky,
    obj_prefix_fortuitous,
    obj_prefix_sturdy,
    obj_prefix_reinforced,
    obj_prefix_precise,
    obj_prefix_skilled,
    obj_prefix_jagged,
    obj_prefix_brutal,

    obj_suffix_initiate_questor,
    obj_suffix_advanced_questor,
    obj_suffix_master_questor,
    obj_suffix_skilled,
    obj_suffix_skillful,
    obj_suffix_experienced,
    obj_suffix_initiate_mage,
    obj_suffix_advanced_mage,
    obj_suffix_master_mage,
    obj_suffix_swallow,
    obj_suffix_hawk,
    obj_suffix_falcon,
    obj_suffix_devastation,
    obj_suffix_annihilation,
    obj_suffix_arcane_power,
    obj_suffix_mystical_power,
    obj_suffix_hexxing,
	obj_suffix_restorative,
	obj_suffix_mystic,

    size, // don't touch
    first = 0 // don't touch
};

} // namespace affect

