/***************************************************************************
 *  Original Diku Mud copyright (C) 1990, 1991 by Sebastian Hammer,        *
 *  Michael Seifert, Hans Henrik St{rfeldt, Tom Madsen, and Katja Nyboe.   *
 *                                                                         *
 *  Merc Diku Mud improvments copyright (C) 1992, 1993 by Michael          *
 *  Chastain, Michael Quan, and Mitchell Tse.                              *
 *                                                                         *
 *  In order to use any part of this Merc Diku Mud, you must comply with   *
 *  both the original Diku license in 'license.doc' as well the Merc       *
 *  license in 'license.txt'.  In particular, you may not remove either of *
 *  these copyright notices.                                               *
 *                                                                         *
 *  Much time and thought has gone into this software and you are          *
 *  benefitting.  We hope that you share your changes too.  What goes      *
 *  around, comes around.                                                  *
 ***************************************************************************/

/***************************************************************************
*       ROM 2.4 is copyright 1993-1995 Russ Taylor                         *
*       ROM has been brought to you by the ROM consortium                  *
*           Russ Taylor (rtaylor@pacinfo.com)                              *
*           Gabrielle Taylor (gtaylor@pacinfo.com)                         *
*           Brian Moore (rom@rom.efn.org)                                  *
*       By using this code, you have agreed to follow the terms of the     *
*       ROM license, in the file Rom24/doc/rom.license                     *
***************************************************************************/

/* this is a listing of all the commands and command related data */

#define COM_INGORE      1


/*
 * Structure for a command in the command lookup table.
 */
struct  cmd_type
{
    char * const        name;
    DO_FUN *            do_fun;
    sh_int              position;
    sh_int              log;
    sh_int              show;
    unsigned int	group;
};

/* the command table itself */
extern  const   struct  cmd_type        cmd_table       [];

/*
 * Command functions.
 * Defined anywhere we please. ;-)
 */

DECLARE_DO_FUN( do_accept	);
DECLARE_DO_FUN( do_addapply	);
DECLARE_DO_FUN( do_addexit	);
DECLARE_DO_FUN( do_adjust       );
DECLARE_DO_FUN( do_advance      );
DECLARE_DO_FUN( do_affects      );
DECLARE_DO_FUN( do_afk          );
DECLARE_DO_FUN( do_alia         );
DECLARE_DO_FUN( do_alias        );
DECLARE_DO_FUN( do_align        );
DECLARE_DO_FUN( do_allow        );
DECLARE_DO_FUN( do_allsave      );
DECLARE_DO_FUN( do_alternate    );
DECLARE_DO_FUN( do_announce     );
DECLARE_DO_FUN( do_answer       );
DECLARE_DO_FUN( do_areas        );
DECLARE_DO_FUN( do_at           );
DECLARE_DO_FUN( do_auction      );
DECLARE_DO_FUN( do_aura         );
DECLARE_DO_FUN( do_autoassist   );
DECLARE_DO_FUN( do_autoboot     );
DECLARE_DO_FUN( do_autoexit     );
DECLARE_DO_FUN( do_autogold     );
DECLARE_DO_FUN( do_autolist     );
DECLARE_DO_FUN( do_autoloot     );
DECLARE_DO_FUN( do_autopeek     );
DECLARE_DO_FUN( do_autorecall   );
DECLARE_DO_FUN( do_autosac      );
DECLARE_DO_FUN( do_autosplit    );
DECLARE_DO_FUN( do_autotick     );
DECLARE_DO_FUN( do_autograph	);
DECLARE_DO_FUN( do_backstab     );
DECLARE_DO_FUN( do_backup       );
DECLARE_DO_FUN( do_balance      );
DECLARE_DO_FUN( do_bamfin       );
DECLARE_DO_FUN( do_bamfout      );
DECLARE_DO_FUN( do_ban          );
DECLARE_DO_FUN( do_bash         );
DECLARE_DO_FUN( do_battle       );
DECLARE_DO_FUN( do_berserk      );
DECLARE_DO_FUN( do_shoot          );
DECLARE_DO_FUN( do_brandish     );
DECLARE_DO_FUN( do_breakup	);
DECLARE_DO_FUN( do_brew         );
DECLARE_DO_FUN( do_brief        );
DECLARE_DO_FUN( do_bug          );
DECLARE_DO_FUN( do_buy          );
DECLARE_DO_FUN( do_canmakebag   );
DECLARE_DO_FUN( do_cast         );
DECLARE_DO_FUN( do_cedit        );
DECLARE_DO_FUN( do_censor	);
DECLARE_DO_FUN( do_changes      );
DECLARE_DO_FUN( do_channels     );
DECLARE_DO_FUN( do_chatmode     );
DECLARE_DO_FUN( do_check        );
DECLARE_DO_FUN( do_chown        );
DECLARE_DO_FUN( do_circle       );
DECLARE_DO_FUN( do_clan_recall  );
DECLARE_DO_FUN( do_clandeposit  );
DECLARE_DO_FUN( do_clanwithdraw );
DECLARE_DO_FUN( do_claninfo  	);
DECLARE_DO_FUN( do_clanlist     );
DECLARE_DO_FUN( do_clanpower	);
DECLARE_DO_FUN( do_clanqp	);
DECLARE_DO_FUN( do_clantalk     );
DECLARE_DO_FUN( do_clear        );
DECLARE_DO_FUN( do_clone        );
DECLARE_DO_FUN( do_close        );
/*
probably don't need this twice
DECLARE_DO_FUN( do_close        );
*/
DECLARE_DO_FUN( do_color        );
DECLARE_DO_FUN( do_combine      );
DECLARE_DO_FUN( do_commands     );
DECLARE_DO_FUN( do_compact      );
DECLARE_DO_FUN( do_compare      );
DECLARE_DO_FUN( do_consider     );
DECLARE_DO_FUN( do_config	);
DECLARE_DO_FUN( do_convert      );
DECLARE_DO_FUN( do_count        );
DECLARE_DO_FUN( do_copyove	);
DECLARE_DO_FUN( do_copyover	);
DECLARE_DO_FUN( do_credits      );
DECLARE_DO_FUN( do_critical_blow);
DECLARE_DO_FUN( do_create       );
DECLARE_DO_FUN( do_crush        );
DECLARE_DO_FUN( do_ctest        );
DECLARE_DO_FUN( do_deaf         );
DECLARE_DO_FUN( do_debug        );
DECLARE_DO_FUN( do_defensive    );
DECLARE_DO_FUN( do_delet        );
DECLARE_DO_FUN( do_delete       );
DECLARE_DO_FUN( do_deny         );
DECLARE_DO_FUN( do_departed     );
DECLARE_DO_FUN( do_departedlist );
DECLARE_DO_FUN( do_deposit      );
DECLARE_DO_FUN( do_deputize	);
DECLARE_DO_FUN( do_description  );
DECLARE_DO_FUN( do_despell      );
DECLARE_DO_FUN( do_dirt         );
DECLARE_DO_FUN( do_disable      );
DECLARE_DO_FUN( do_disarm       );
DECLARE_DO_FUN( do_disconnect   );
DECLARE_DO_FUN( do_divorce      );
DECLARE_DO_FUN( do_donate       );
DECLARE_DO_FUN( do_doas		);
DECLARE_DO_FUN( do_down         );
DECLARE_DO_FUN( do_drag         );
DECLARE_DO_FUN( do_drink        );
DECLARE_DO_FUN( do_drop         );
DECLARE_DO_FUN( do_duel		);
DECLARE_DO_FUN( do_dump         );
DECLARE_DO_FUN( do_east         );
DECLARE_DO_FUN( do_eat          );
DECLARE_DO_FUN( do_echo         );
DECLARE_DO_FUN( do_edit         );
DECLARE_DO_FUN( do_email        );
DECLARE_DO_FUN( do_emote        );
DECLARE_DO_FUN( do_engrave      );
DECLARE_DO_FUN( do_enter        );
DECLARE_DO_FUN( do_envenom      );
DECLARE_DO_FUN( do_equipment    );
DECLARE_DO_FUN( do_evolve	    );
DECLARE_DO_FUN( do_evoset       );
DECLARE_DO_FUN( do_examine      );
DECLARE_DO_FUN( do_exits        );
DECLARE_DO_FUN( do_exlist       );
DECLARE_DO_FUN( do_extraset     );
DECLARE_DO_FUN( do_familiar     );
DECLARE_DO_FUN( do_file         );
DECLARE_DO_FUN( do_fill         );
DECLARE_DO_FUN( do_finger	);
DECLARE_DO_FUN( do_fingerinfo   );
DECLARE_DO_FUN( do_firebuilding );
DECLARE_DO_FUN( do_flag         );
DECLARE_DO_FUN( do_flaglist     );
DECLARE_DO_FUN( do_flagsearch	);
DECLARE_DO_FUN( do_flame        );
DECLARE_DO_FUN( do_flee         );
DECLARE_DO_FUN( do_fly          );
DECLARE_DO_FUN( do_fod          );
DECLARE_DO_FUN( do_follow       );
DECLARE_DO_FUN( do_followerlist );
DECLARE_DO_FUN( do_for          );
DECLARE_DO_FUN( do_force        );
DECLARE_DO_FUN( do_forge        );
DECLARE_DO_FUN( do_freeze       );
DECLARE_DO_FUN( do_fry          );
DECLARE_DO_FUN( do_fuckoff      );
DECLARE_DO_FUN( do_fyi          );
DECLARE_DO_FUN( do_gain         );
DECLARE_DO_FUN( do_gamein       );
DECLARE_DO_FUN( do_gameout      );
DECLARE_DO_FUN( do_get          );
DECLARE_DO_FUN( do_give         );
DECLARE_DO_FUN( do_globalsocial );
DECLARE_DO_FUN( do_gossip       );
DECLARE_DO_FUN( do_goto         );
DECLARE_DO_FUN( do_grant        );
DECLARE_DO_FUN( do_grantlist    );
DECLARE_DO_FUN( do_grats        );
DECLARE_DO_FUN( do_group        );
DECLARE_DO_FUN( do_grouplist    );
DECLARE_DO_FUN( do_groups       );
DECLARE_DO_FUN( do_gtell        );
DECLARE_DO_FUN( do_guild        );
DECLARE_DO_FUN( do_hammerstrike );
DECLARE_DO_FUN( do_hbb          );
DECLARE_DO_FUN( do_hbi          );
DECLARE_DO_FUN( do_heal         );
DECLARE_DO_FUN( do_heed         );
DECLARE_DO_FUN( do_hedit        );
DECLARE_DO_FUN( do_help         );
DECLARE_DO_FUN( do_hide         );
DECLARE_DO_FUN( do_hone         );
DECLARE_DO_FUN( do_hunt         );
DECLARE_DO_FUN( do_ic		);
DECLARE_DO_FUN( do_iclantalk    );
DECLARE_DO_FUN( do_idea         );
DECLARE_DO_FUN( do_identify     );
DECLARE_DO_FUN( do_ignore	);
DECLARE_DO_FUN( do_immname      );
DECLARE_DO_FUN( do_immtalk      );
DECLARE_DO_FUN( do_immapp	);
DECLARE_DO_FUN( do_imotd        );
DECLARE_DO_FUN( do_inset	);
DECLARE_DO_FUN( do_inventory    );
DECLARE_DO_FUN( do_invis        );
DECLARE_DO_FUN( do_invite       );
DECLARE_DO_FUN( do_join         );
DECLARE_DO_FUN( do_junk         );
DECLARE_DO_FUN( do_kewlscore    );
DECLARE_DO_FUN( do_kick         );
DECLARE_DO_FUN( do_kill         );
DECLARE_DO_FUN( do_lag          );
DECLARE_DO_FUN( do_land         );
DECLARE_DO_FUN( do_lay_on_hands );
DECLARE_DO_FUN( do_leader       );
DECLARE_DO_FUN( do_levels       );
DECLARE_DO_FUN( do_linkload     );
DECLARE_DO_FUN( do_list         );
DECLARE_DO_FUN( do_load         );
DECLARE_DO_FUN( do_loadhelps	);
DECLARE_DO_FUN( do_update	);
DECLARE_DO_FUN( do_lock         );
DECLARE_DO_FUN( do_locker       );
DECLARE_DO_FUN( do_log          );
DECLARE_DO_FUN( do_look         );
DECLARE_DO_FUN( do_lore         );
DECLARE_DO_FUN( do_lower        );
DECLARE_DO_FUN( do_lurk		    );
DECLARE_DO_FUN( do_mark         );
DECLARE_DO_FUN( do_marry        );
DECLARE_DO_FUN( do_master       );
DECLARE_DO_FUN( do_memory       );
DECLARE_DO_FUN( do_mfind        );
DECLARE_DO_FUN( do_mlevel       );
DECLARE_DO_FUN( do_mload        );
DECLARE_DO_FUN( do_morph        );
DECLARE_DO_FUN( do_motd         );
DECLARE_DO_FUN( do_mpasound     );
DECLARE_DO_FUN( do_mpat         );
DECLARE_DO_FUN( do_mpcast       );
DECLARE_DO_FUN( do_mpclearmoney );
DECLARE_DO_FUN( do_mpecho       );
DECLARE_DO_FUN( do_mpechoaround );
DECLARE_DO_FUN( do_mpechoat     );
DECLARE_DO_FUN( do_mpforce      );
DECLARE_DO_FUN( do_mpgoto       );
DECLARE_DO_FUN( do_mpjunk       );
DECLARE_DO_FUN( do_mpkill       );
DECLARE_DO_FUN( do_mpmload      );
DECLARE_DO_FUN( do_mpoload      );
DECLARE_DO_FUN( do_mppurge      );
DECLARE_DO_FUN( do_mpstat       );
DECLARE_DO_FUN( do_mptransfer   );
DECLARE_DO_FUN( do_mset         );
DECLARE_DO_FUN( do_mstat        );
DECLARE_DO_FUN( do_music        );
DECLARE_DO_FUN( do_mwhere       );
//DECLARE_DO_FUN( do_mypipe	);
DECLARE_DO_FUN( do_newbiekit    );
DECLARE_DO_FUN( do_newlock      );
DECLARE_DO_FUN( do_newpasswd    );
DECLARE_DO_FUN( do_immquest     );
DECLARE_DO_FUN( do_next         );
DECLARE_DO_FUN( do_nofollow     );
DECLARE_DO_FUN( do_noloot       );
DECLARE_DO_FUN( do_noreply      );
DECLARE_DO_FUN( do_north        );
DECLARE_DO_FUN( do_nosummon     );
DECLARE_DO_FUN( do_note         );
DECLARE_DO_FUN( do_notify       );
DECLARE_DO_FUN( do_oclone       );
DECLARE_DO_FUN( do_ofind        );
DECLARE_DO_FUN( do_olevel       );
DECLARE_DO_FUN( do_oload        );
DECLARE_DO_FUN( do_ooc          );
DECLARE_DO_FUN( do_open         );
DECLARE_DO_FUN( do_order        );
DECLARE_DO_FUN( do_oset         );
DECLARE_DO_FUN( do_ostat        );
DECLARE_DO_FUN( do_outfit       );
DECLARE_DO_FUN( do_owhere       );
DECLARE_DO_FUN( do_owner        );
DECLARE_DO_FUN( do_page         );
DECLARE_DO_FUN( do_paintbow     );
DECLARE_DO_FUN( do_pardon       );
DECLARE_DO_FUN( do_password     );
DECLARE_DO_FUN( do_peace        );
DECLARE_DO_FUN( do_pecho        );
DECLARE_DO_FUN( do_peek         );
DECLARE_DO_FUN( do_personal     );
DECLARE_DO_FUN( do_permit	);
DECLARE_DO_FUN( do_pet          );
DECLARE_DO_FUN( do_pick         );
DECLARE_DO_FUN( do_ping         );
DECLARE_DO_FUN( do_pipe		);
DECLARE_DO_FUN( do_pit          );
DECLARE_DO_FUN( do_pk           );
DECLARE_DO_FUN( do_play         );
DECLARE_DO_FUN( do_pmote        );
DECLARE_DO_FUN( do_pocket	);
DECLARE_DO_FUN( do_pose         );
DECLARE_DO_FUN( do_pour         );
DECLARE_DO_FUN( do_practice     );
DECLARE_DO_FUN( do_pray         );
DECLARE_DO_FUN( do_prefi        );
DECLARE_DO_FUN( do_prefix       );
DECLARE_DO_FUN( do_printhelps	);
DECLARE_DO_FUN( do_private      );
DECLARE_DO_FUN( do_prompt       );
DECLARE_DO_FUN( do_propose	);
DECLARE_DO_FUN( do_protect      );
DECLARE_DO_FUN( do_pstat        );
DECLARE_DO_FUN( do_punish	);
DECLARE_DO_FUN( do_purge        );
DECLARE_DO_FUN( do_push         );
DECLARE_DO_FUN( do_put          );
DECLARE_DO_FUN( do_qpconv	);
DECLARE_DO_FUN( do_qtell        );
DECLARE_DO_FUN( do_quaff        );
DECLARE_DO_FUN( do_query        );
DECLARE_DO_FUN( do_quest        );
DECLARE_DO_FUN( do_question     );
DECLARE_DO_FUN( do_qui          );
DECLARE_DO_FUN( do_quiet        );
DECLARE_DO_FUN( do_quit         );
DECLARE_DO_FUN( do_qwest        );
DECLARE_DO_FUN( do_raffset      );
DECLARE_DO_FUN( do_rage         );
DECLARE_DO_FUN( do_rank         );
DECLARE_DO_FUN( do_rchat        );
DECLARE_DO_FUN( do_rconnect     );
DECLARE_DO_FUN( do_rdebug       );
DECLARE_DO_FUN( do_rdisconnect  );
DECLARE_DO_FUN( do_read         );
DECLARE_DO_FUN( do_read_finger  );
DECLARE_DO_FUN( do_reboo        );
DECLARE_DO_FUN( do_reboot       );
DECLARE_DO_FUN( do_recall       );
DECLARE_DO_FUN( do_recho        );
DECLARE_DO_FUN( do_recite       );
DECLARE_DO_FUN( do_reject	);
//DECLARE_DO_FUN( do_reload       );
DECLARE_DO_FUN( do_relevel      );
DECLARE_DO_FUN( do_relocate     );
DECLARE_DO_FUN( do_remort       );
DECLARE_DO_FUN( do_remexit	);
DECLARE_DO_FUN( do_eremort	);
DECLARE_DO_FUN( do_remove       );
DECLARE_DO_FUN( do_rename       );
DECLARE_DO_FUN( do_repair       );
DECLARE_DO_FUN( do_replay       );
DECLARE_DO_FUN( do_reply        );
DECLARE_DO_FUN( do_report       );
DECLARE_DO_FUN( do_rescue       );
DECLARE_DO_FUN( do_rest         );
DECLARE_DO_FUN( do_restore      );
DECLARE_DO_FUN( do_return       );
DECLARE_DO_FUN( do_revoke	);
DECLARE_DO_FUN( do_ridea	);
DECLARE_DO_FUN( do_rignore      );
DECLARE_DO_FUN( do_rlist        );
DECLARE_DO_FUN( do_roleplay     );
DECLARE_DO_FUN( do_roomexits    );
DECLARE_DO_FUN( do_roomlist     );
DECLARE_DO_FUN( do_rotate       );
DECLARE_DO_FUN( do_rppaward     );
DECLARE_DO_FUN( do_rreply       );
DECLARE_DO_FUN( do_rset         );
DECLARE_DO_FUN( do_rsockets     );
DECLARE_DO_FUN( do_rstat        );
DECLARE_DO_FUN( do_rtell        );
DECLARE_DO_FUN( do_rules        );
DECLARE_DO_FUN( do_rwhere       );
DECLARE_DO_FUN( do_rwho         );
DECLARE_DO_FUN( do_sacrifice    );
DECLARE_DO_FUN( do_save         );
DECLARE_DO_FUN( do_say          );
DECLARE_DO_FUN( do_scan         );
DECLARE_DO_FUN( do_scan2         );
DECLARE_DO_FUN( do_scatter	);
DECLARE_DO_FUN( do_scon         );
DECLARE_DO_FUN( do_score        );
DECLARE_DO_FUN( do_scribe       );
DECLARE_DO_FUN( do_scroll       );
DECLARE_DO_FUN( do_second       );
DECLARE_DO_FUN( do_secure       );
DECLARE_DO_FUN( do_sectchange	);
DECLARE_DO_FUN( do_sedit        );
DECLARE_DO_FUN( do_sell         );
DECLARE_DO_FUN( do_send_announce);
DECLARE_DO_FUN( do_set          );
DECLARE_DO_FUN( do_setgamein    );
DECLARE_DO_FUN( do_setgameout   );
DECLARE_DO_FUN( do_shadow       );
//DECLARE_DO_FUN( do_shoot        );
DECLARE_DO_FUN( do_show         );
DECLARE_DO_FUN( do_showflags    );
DECLARE_DO_FUN( do_showlast     );
DECLARE_DO_FUN( do_showlost     );
DECLARE_DO_FUN( do_showraff     );
DECLARE_DO_FUN( do_shutdow      );
DECLARE_DO_FUN( do_shutdown     );
DECLARE_DO_FUN( do_sing         );
DECLARE_DO_FUN( do_sit          );
DECLARE_DO_FUN( do_skills       );
DECLARE_DO_FUN( do_skillpoint   );
DECLARE_DO_FUN( do_sla          );
DECLARE_DO_FUN( do_slay         );
DECLARE_DO_FUN( do_sleep        );
DECLARE_DO_FUN( do_slookup      );
DECLARE_DO_FUN( do_smite        );
DECLARE_DO_FUN( do_smote        );
DECLARE_DO_FUN( do_sneak        );
DECLARE_DO_FUN( do_snoop        );
DECLARE_DO_FUN( do_socials      );
DECLARE_DO_FUN( do_sockets      );
DECLARE_DO_FUN( do_south        );
DECLARE_DO_FUN( do_spells       );
DECLARE_DO_FUN( do_split        );
DECLARE_DO_FUN( do_spousegate   );
DECLARE_DO_FUN( do_spousetalk   );
DECLARE_DO_FUN( do_sset         );
DECLARE_DO_FUN( do_stand        );
DECLARE_DO_FUN( do_stat         );
DECLARE_DO_FUN( do_steal        );
DECLARE_DO_FUN( do_storage	);
DECLARE_DO_FUN( do_story        );
DECLARE_DO_FUN( do_string       );
DECLARE_DO_FUN( do_strongbox    );
DECLARE_DO_FUN( do_superwiz     );
DECLARE_DO_FUN( do_swho         );
DECLARE_DO_FUN( do_switch       );
DECLARE_DO_FUN( do_tail         );
DECLARE_DO_FUN( do_tell         );
DECLARE_DO_FUN( do_testpose     );
DECLARE_DO_FUN( do_time         );
DECLARE_DO_FUN( do_title        );
DECLARE_DO_FUN( do_train        );
DECLARE_DO_FUN( do_trade	);
DECLARE_DO_FUN( do_transfer     );
DECLARE_DO_FUN( do_trip         );
DECLARE_DO_FUN( do_typelist     );
DECLARE_DO_FUN( do_typo         );
DECLARE_DO_FUN( do_unalias      );
DECLARE_DO_FUN( do_undeny	);
DECLARE_DO_FUN( do_unjoin       );
DECLARE_DO_FUN( do_unlock       );
DECLARE_DO_FUN( do_unread       );
DECLARE_DO_FUN( do_up           );
DECLARE_DO_FUN( do_value        );
DECLARE_DO_FUN( do_video        );
DECLARE_DO_FUN( do_violate      );
DECLARE_DO_FUN( do_visible      );
DECLARE_DO_FUN( do_vlist        );
DECLARE_DO_FUN( do_vnum         );
DECLARE_DO_FUN( do_vt100        );
DECLARE_DO_FUN( do_wake         );
DECLARE_DO_FUN( do_war		);
DECLARE_DO_FUN( do_wbb		);
DECLARE_DO_FUN( do_wbi		);
DECLARE_DO_FUN( do_wear         );
DECLARE_DO_FUN( do_weather      );
DECLARE_DO_FUN( do_weddingring  );
DECLARE_DO_FUN( do_west         );
DECLARE_DO_FUN( do_where        );
DECLARE_DO_FUN( do_whisper      );
DECLARE_DO_FUN( do_who          );
DECLARE_DO_FUN( do_whois        );
DECLARE_DO_FUN( do_wimpy        );
DECLARE_DO_FUN( do_withdraw     );
DECLARE_DO_FUN( do_wizgroup     );
DECLARE_DO_FUN( do_wizhelp      );
DECLARE_DO_FUN( do_wizify       );
DECLARE_DO_FUN( do_wizlist      );
DECLARE_DO_FUN( do_wizlock      );
DECLARE_DO_FUN( do_wiznet       );
DECLARE_DO_FUN( do_worth        );
DECLARE_DO_FUN( do_work		);
DECLARE_DO_FUN( do_yell         );
DECLARE_DO_FUN( do_zap          );
DECLARE_DO_FUN( do_zecho        );


